esphome:
  name: block-prihozka
  friendly_name: Block_Prihozka 

esp8266:
  board: d1_mini
  restore_from_flash: true

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "KOWDAA8XBu8jM5F884wvQ6ji5Mhwm2J29yZXx2C9Kko="

ota:
  - platform: esphome
    password: "9aa6e161a6c491657f320a1b15fde731"

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    - ssid: Keenetic-Home
      password: "9994554500"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Block-Prihozka Fallback Hotspot"
    password: "mXyPb1kexKGo"

udp:

captive_portal:

# ================= TIME ====================================
time:
  - platform: sntp
    id: ntp_time
    timezone: Asia/Omsk
    servers:
      - 0.openwrt.pool.ntp.org
      - 1.openwrt.pool.ntp.org
      - 2.openwrt.pool.ntp.org

# ===============================================================
button:
  - platform: restart
    name: Restart 

text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP Address
    ssid:
      name: SSID
# ================== Init relay ================================
switch:
  - platform: gpio
    id: switch_5
    name: Реле 5
    icon: mdi:water-boiler
    pin:
      number: GPIO16
      inverted: false
      mode:
        output: true
    restore_mode: ALWAYS_OFF

  - platform: gpio
    id: switch_1
    name: Реле 1
    icon: mdi:water-boiler
    pin:
      number: GPIO5
      inverted: false
      mode:
        output: true
    restore_mode: ALWAYS_OFF

  - platform: gpio
    id: switch_2
    name: Реле 2
    icon: mdi:water-boiler
    pin:
      number: GPIO4
      inverted: false
      mode:
        output: true
    restore_mode: ALWAYS_OFF

  - platform: gpio
    id: switch_3
    name: Реле 3
    icon: mdi:water-boiler
    pin:
      number: GPIO0
      inverted: false
      mode:
        output: true
    restore_mode: ALWAYS_OFF

  - platform: gpio
    id: switch_4
    name: Реле 4
    icon: mdi:water-boiler
    pin:
      number: GPIO2
      inverted: false
      mode:
        output: true
    restore_mode: ALWAYS_OFF

# ============== Init DS18B20 & DHT11 (датчики температуры) ====================
one_wire:
  - platform: gpio
    pin: GPIO12

sensor:
  # DS18B20
  - platform: dallas_temp
    address: 0x687c70190264ff28
    name: Датчик температуры холл
    id: sensor_holl_temp
    update_interval: 1s
    unit_of_measurement: "°C"
    icon: mdi:thermometer
    device_class: "temperature"
    state_class: "measurement"
    accuracy_decimals: 1
  
  # DHT11
  - platform: dht
    pin: GPIO14
    id: dht11_dvor_sensor
    model: DHT11
    temperature:
      name: "Dvor Temperature"
      id: dvor_temp
      filters:
        - lambda: return x - 4;
      unit_of_measurement: °C
    humidity:
      id: dvor_hum
      name: "Dvor Humidity"
      unit_of_measurement: '%'
    update_interval: 5s

  # # Сенсор времени ESPHOME
  # - platform: template
  #   name: "Current time"
  #   lambda: |-
  #     char str[17];
  #     time_t currTime = id(ntp_time).now().timestamp;
  #     strftime(str, sizeof(str), "%Y-%m-%d %X", localtime(&currTime));
  #     return  { str };
  #   update_interval: 60s

# ======================== Ночники ===========================================
output:
  - platform: esp8266_pwm
    pin: GPIO13
    frequency: 1000 Hz
    id: pwm_output1

  - platform: esp8266_pwm
    pin: GPIO15
    frequency: 1000 Hz
    id: pwm_output2

light:
  - platform: monochromatic
    output: pwm_output1
    name: "Night Light"
    restore_mode: RESTORE_DEFAULT_OFF 

  - platform: monochromatic
    output: pwm_output2
    name: "Night Light2"
    restore_mode: RESTORE_DEFAULT_OFF
# ================================================================================