esphome:
  name: display-test
  friendly_name: Display_test
  on_boot:
    then: 
#  Зажигать подсветку при загрузке


esp8266:
  board: nodemcuv2
  restore_from_flash: true

preferences:
  flash_write_interval: 1min
# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "XTWSYHtIasFyHveYWqRqvhauIX42o7TqmOT1Ltvqsx0="

ota:
  password: "135dd3035c02ef5860f78cbb264ec90f"

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    - ssid: OpenWrt_Garage
      password: "9514210798"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Display-Test Fallback Hotspot"
    password: "T4cTtQZNA6cP"

captive_portal:

time:
  - platform: homeassistant
    id: homeassistant_time

display:
    platform: tm1638
    id: tm1637_display
    clk_pin: D6
    dio_pin: D5
    stb_pin: D7
    intensity: 5
    update_interval: 500ms
    lambda: |-
      static int i = 0;
      i++;
      if ((i % 2) == 0)
        it.strftime("%H%M", id(homeassistant_time).now());
      else
        it.strftime("%H%M", id(homeassistant_time).now());