esphome:
  name: electric-kettle

esp8266:
  board: nodemcuv2
  restore_from_flash: true

preferences:
  flash_write_interval: 1min

globals:
  - id: initial_temp
    type: float
    restore_value: no
    initial_value: '0'
  - id: heating_start_time
    type: uint32
    restore_value: no
    initial_value: '0'

# Enable Home Assistant API
api:
  encryption:
    key: "XTWSYHtIasFzHveYWqRqvhauIX42o7TqnOT1Ltvqsx0="
logger:

ota:
  platform: esphome
  password: "135dd3035c02ef5860f78cbb264ec92f"

wifi:
  manual_ip:
    static_ip: 192.168.1.138
    gateway: 192.168.1.1
    subnet: 255.255.255.0
  use_address: 192.168.1.138  # Используйте IP вместо .local
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    - ssid: "IoT_Office"
      id: wifi_id
      password: "9514210798"
    - ssid: Keenetic-Home
      password: "9994554500"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Electric kettle Fallback Hotspot"
    password: "00000000"



# Отключить mDNS
mdns:
  disabled: true
captive_portal:

number:
  - platform: template
    name: "Температура выключения"
    id: target_temp
    optimistic: true
    min_value: 20
    max_value: 100
    step: 1
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-check"
    restore_value: yes

output:
  - platform: esp8266_pwm
    frequency: 10000 Hz
    pin: GPIO01
    inverted: true
    id: rtttl_out

rtttl:
  output: rtttl_out

# Защита от пустого чайника
script:
  - id: check_temp_rise
    then:
      - delay: 60s  # Через 2 минуты смотрим
      - if:
          condition:
            and:
              - switch.is_on: relay
              - lambda: 'return id(sensor_kettle_temp).state - id(initial_temp) < 2;' # Если температура не поднялас на 2 градусов
          then:
            - switch.turn_off: relay   # Выключаем нагреватель

switch:
  - platform: gpio
    internal: true
    pin: 
      number: GPIO00
      inverted: true
      mode:
        output: true
    name: "Нагрев"
    id: relay
    restore_mode: RESTORE_DEFAULT_OFF
    icon: mdi:kettle-steam-outline
    on_turn_on:
      - rtttl.play: 'scale_up:d=32,o=5,b=100:c,d,e,f,g'
      - globals.set:
          id: initial_temp
          value: !lambda 'return id(sensor_kettle_temp).state;'
      - globals.set:
          id: heating_start_time
          value: !lambda 'return millis();'
      - script.execute: check_temp_rise
    on_turn_off:
      
      - script.stop: check_temp_rise

# ============== Init DS18B20 (датчики температуры) ====================
one_wire:
  - platform: gpio
    pin: GPIO2

sensor:
  - platform: dallas_temp
    address: 0x048999bd0164ff28
    name: Температура чайника
    id: sensor_kettle_temp
    update_interval: 2s
    unit_of_measurement: "°C"
    icon: mdi:thermometer
    device_class: "temperature"
    state_class: "measurement"
    accuracy_decimals: 1
    on_value:
      then:
        - if:
            condition:
              and:
                - switch.is_on: relay
                - lambda: 'return x >= id(target_temp).state;'
            then:
              - switch.turn_off: relay
              - rtttl.play: 'take_on:d=8,o=5,b=160:f#,f#,f#,d,p,b4,p,e,p,e,p,e,g#,g#,a,b,a,a,a,e,p,d,p,f#,p,f#,p,f#,e,e,f#,e,f#,f#,f#,d,p,b4,p,e,p,e,p,e,g#,g#,a,b,a,a,a,e,p,d,p,f#,p,f#,p,f#,e,e5'

  - platform: template
    name: "Время нагрева"
    id: heating_time
    unit_of_measurement: "с"
    icon: "mdi:clock-outline"
    update_interval: 1s
    lambda: !lambda |-
      if (id(relay).state) {
        return (millis() - id(heating_start_time)) / 1000.0;
      } else {
        return 0.0;
      }


button:
  - platform: template
    id: heat_kettle_button
    name: "Нагреть"
    icon: mdi:kettle-steam-outline
    on_press:
      - switch.toggle: relay

  - platform: restart
    name: Restart 
    id: reboot

text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP Address
    ssid:
      name: SSID

binary_sensor:
  - platform: gpio
    id: binary_button
    internal: true
    filters:
      - delayed_on_off: 50ms
    pin:
      number: GPIO03
      inverted: false
      mode: INPUT

    on_press:
      then:
        - rtttl.play: 'button_click:d=32,o=6,b=100:c,p,c'

    on_multi_click:
      - timing:
            - ON for at least 1.0s
        then:
            - switch.toggle: relay
            - if:
                condition:
                  - switch.is_off: relay
                then: 
                  - rtttl.play: 'scale_down:d=32,o=5,b=100:g,f,e,d,c'