esphome:
  name: garage-kotel

bk72xx:
  board: generic-bk7231t-qfn32-tuya

api:
  encryption:
    key: "A+xLM79G2f7hVt1VqNu2u090EHyfxqGEUhjZ1ZYKH9I="
  reboot_timeout: 1800s

ota:
  platform: esphome

udp:
  id: udp_hub

packet_transport:
  - platform: udp
    binary_sensors:
      - kotel_state



logger:
wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    - ssid: OpenWrt_Garage
      password: "9514210798"
      manual_ip:
        static_ip: 192.168.1.216
        gateway: 192.168.1.1
        subnet: 255.255.255.0
        dns1: 77.88.8.8

  use_address: 192.168.1.216
  ap:
    ssid: "Garage Kotel Hotspot"
    password: "00000000"

time:

  - platform: sntp
    id: ntp_time
    timezone: UTC-06:00
    servers:
      - 0.openwrt.pool.ntp.org
      - 1.openwrt.pool.ntp.org
      - 2.openwrt.pool.ntp.org
button:
  - platform: restart
    name: Restart

text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP Address
    ssid:
      name: SSID

  # Сенсор времени ESPHOME
  - platform: template
    name: "Current time"
    lambda: |-
      char str[17];
      time_t currTime = id(ntp_time).now().timestamp;
      strftime(str, sizeof(str), "%Y-%m-%d %X", localtime(&currTime));
      return std::string(str);
    update_interval: 60s

sensor:
  - platform: uptime
    name: Uptime

  - platform: packet_transport
    provider: co2-sensor-garage
    remote_id: garage_temp
    id: garage_temp
    internal: true

  - platform: packet_transport
    provider: co2-sensor-garage
    remote_id: garage_hum
    id: garage_hum
    internal: true

# ================== Счетик времени включенного котла =======================
  - platform: duty_time
    id: kotel_work_time
    name: Время работы котла
    icon: mdi:alarm-plus
    update_interval: 10s
    accuracy_decimals: 0
    device_class: duration
    lambda: "return id(switch_1).state;"
    restore: true
    last_time:
      name: Kotel посл. время работы
# ===================================================================================
  - platform: wifi_signal
    name: WiFi Strength ${device_name}
    update_interval: 60s
    id: wifi_signal_db

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"
    device_class: ""

binary_sensor:
  - platform: gpio
    id: binary_switch_1
    pin:
      number: P6
      inverted: true
      mode: INPUT_PULLUP
    on_state:
      then:
        - lambda: |-
            static bool last_state = false;
            if (x && !last_state) {  // Нажатие кнопки (переход в true)
              auto call = id(thermostat_garage_kotel).make_call();
              if (id(thermostat_garage_kotel).mode == climate::CLIMATE_MODE_HEAT) {
                call.set_mode(climate::CLIMATE_MODE_OFF);
              } else {
                call.set_mode(climate::CLIMATE_MODE_HEAT);
              }
              call.perform();
            }
            last_state = x;

  # Бинарный сенсор для публикации состояния термостата
  - platform: template
    id: kotel_state
    name: Kotel state
    internal: false
    lambda: |-
      if (id(thermostat_garage_kotel).mode == climate::CLIMATE_MODE_HEAT) {
        return true;  // ON когда в режиме HEAT
      } else {
        return false; // OFF для всех других режимов
      }

  # Бинарный сенсор для приема команды с pcf8574
  - platform: packet_transport
    id: kotel_command
    internal: true
    remote_id: kotel_command
    provider: pcf8574
    on_press:
      then:
        - lambda: |-
            auto call = id(thermostat_garage_kotel).make_call();
            call.set_mode(climate::CLIMATE_MODE_HEAT);
            call.perform();
    on_release:
      then:
        - lambda: |-
            auto call = id(thermostat_garage_kotel).make_call();
            call.set_mode(climate::CLIMATE_MODE_OFF);
            call.perform();


switch:
  - platform: gpio
    id: switch_1
    name: Relay 1
    pin: P24

  # Выключатель отпления в пиковую зону
  - platform: template
    name: "Не включать в ПИК"
    optimistic: true
    icon: mdi:clock
    id: switch_peack_off
    restore_mode: RESTORE_DEFAULT_ON

status_led:
  pin:
    number: P7
    inverted: true

# Глобальные переменные для пикового времени
globals:
  - id: thermostat_state_before_peak
    type: bool
    initial_value: 'false'
  - id: in_peak
    type: bool
    initial_value: 'false'

climate:
  - platform: thermostat
    id: thermostat_garage_kotel
    name: "Thermostat Garage Kotel"
    visual:
      min_temperature: 5
      max_temperature: 25
      temperature_step:
        target_temperature: 1.0
        current_temperature: 0.1
    sensor: garage_temp
    humidity_sensor: garage_hum
    min_heating_off_time: 10s
    min_heating_run_time: 10s
    min_idle_time: 10s
    heat_deadband: 1.0
    heat_overrun: 0.0
    heat_action:
      - switch.turn_on: switch_1
    idle_action:
      - switch.turn_off: switch_1
    on_state:
      then:
        - binary_sensor.template.publish:
            id: kotel_state
            state: !lambda 'return x.mode == climate::CLIMATE_MODE_HEAT;'

# Логика пикового времени
interval:
  - interval: 60s
    then:
      lambda: |-
        auto now = id(ntp_time).now();
        if (!now.is_valid()) return;
        
        int hour = now.hour;
        
        // Определяем пиковое время: утро 7:00-10:00, вечер 17:00-21:00
        bool is_peak = (hour >= 7 && hour < 10) || (hour >= 17 && hour < 21);
        bool was_in_peak = id(in_peak);
        
        if (is_peak && !was_in_peak && id(switch_peack_off).state) {
          {
          // Вход в пиковое время - сохраняем состояние
          id(thermostat_state_before_peak) = (id(thermostat_garage_kotel).mode == climate::CLIMATE_MODE_HEAT);
          id(in_peak) = true;
          // Выключаем термостат
          auto call = id(thermostat_garage_kotel).make_call();
          call.set_mode(climate::CLIMATE_MODE_OFF);
          call.perform();
          }
        } else if (!is_peak && was_in_peak) {
          {
          // Выход из пикового времени - восстанавливаем состояние
          id(in_peak) = false;
          if (id(thermostat_state_before_peak)) {
            auto call = id(thermostat_garage_kotel).make_call();
            call.set_mode(climate::CLIMATE_MODE_HEAT);
            call.perform();
          }
          }
        }
