# GPIO0 — кнопка (это понятно, когда мы включали бутлоадер)
# GPIO12 — красный светодиод и реле
# GPIO13 — синий светодиод
# GPIO14 и GPIO4 выведены на разъем подключения датчиков.
substitutions:
  name: garage-konvector

esphome:
  name: ${name}

esp8266:
  board: sonoff_th
  restore_from_flash: true
  
udp:
  id: udp_hub

packet_transport:
  - platform: udp
    # Бинарные сенсоры, которые мы публикуем для других устройств
    binary_sensors:
      - konvector_state

logger:

api:
  encryption:
    key: "Ldm49FmXtWzGqzHLQaf91mkPmK/Ajq1lrKILY05+NgE="

ota:
  - platform: esphome
    password: "0cf2d59e134cf13be87b10fd500c2e19"

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    - ssid: OpenWrt_Garage
      password: "9514210798"
      manual_ip:
        static_ip: 192.168.1.243
        gateway: 192.168.1.1
        subnet: 255.255.255.0
        dns1: 192.168.1.1
  use_address: 192.168.1.243  # Используйте IP вместо .local

# Отключить mDNS
mdns:
  disabled: true

captive_portal:
time:
  - platform: sntp
    id: ntp_time
    timezone: Asia/Omsk
    servers:
      - 0.openwrt.pool.ntp.org
      - 1.openwrt.pool.ntp.org
      - 192.168.1.1 

button:
  - platform: restart
    name: Restart

text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP Address
    ssid:
      name: SSID

  - platform: template
    name: "Current time"
    lambda: |-
      char str[17];
      time_t currTime = id(ntp_time).now().timestamp;
      strftime(str, sizeof(str), "%Y-%m-%d %X", localtime(&currTime));
      return std::string(str);
    update_interval: 60s

light:
  - platform: monochromatic
    name: "Blue LED"
    output: blue_led
    internal: true

switch:
  - platform: gpio
    id: relay
    name: Relay ${name}
    pin: GPIO12

  # Выключатель отпления в пиковую зону
  - platform: template
    name: "Выключать ${name} в ПИК"
    optimistic: true
    icon: mdi:clock
    id: switch_peack_off
    restore_mode: RESTORE_DEFAULT_ON

output:
  - platform: esp8266_pwm
    id: blue_led
    pin: GPIO13
    inverted: True

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Button ${name}"
    internal: true
    on_state:
      then:
        - lambda: |-
            static bool last_state = false;
            if (x && !last_state) {  // Нажатие кнопки (переход в true)
              auto call = id(thermostat_garage_konvector).make_call();
              if (id(thermostat_garage_konvector).mode == climate::CLIMATE_MODE_HEAT) {
                call.set_mode(climate::CLIMATE_MODE_OFF);
              } else {
                call.set_mode(climate::CLIMATE_MODE_HEAT);
              }
              call.perform();
            }
            last_state = x;


# Сенсор для UDP climate ==========================================================================================
  # Бинарный сенсор для публикации состояния термостата
  - platform: template
    id: konvector_state
    name: Konvector state
    internal: false
    lambda: |-
      if (id(thermostat_garage_konvector).mode == climate::CLIMATE_MODE_HEAT) {
        return true;  // ON когда в режиме HEAT
      } else {
        return false; // OFF для всех других режимов
      }
 
  # Бинарный сенсор для приема команды с pcf8574
  - platform: packet_transport
    id: konvector_command
    internal: true
    remote_id: konvector_command
    provider: pcf8574
    on_press:
      then:
        - lambda: |-
            auto call = id(thermostat_garage_konvector).make_call();
            call.set_mode(climate::CLIMATE_MODE_HEAT);
            call.perform();
    on_release:
      then:
        - lambda: |-
            auto call = id(thermostat_garage_konvector).make_call();
            call.set_mode(climate::CLIMATE_MODE_OFF);
            call.perform();

# =================================================================================================================
sensor:
  - platform: packet_transport
    provider: co2-sensor-garage
    remote_id: garage_temp
    id: garage_temp
    internal: true

  - platform: wifi_signal
    name: WiFi Strength
    update_interval: 60s
    id: wifi_signal_db

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"
    device_class: ""

climate:
  - platform: thermostat
    id: thermostat_garage_konvector
    name: "Thermostat ${name}"
    visual:
      min_temperature: 5
      max_temperature: 25
      temperature_step:
        target_temperature: 1.0
        current_temperature: 0.1
    sensor: garage_temp
    min_heating_off_time: 10s
    min_heating_run_time: 10s
    min_idle_time: 10s
    heat_deadband: 1.0
    heat_overrun: 0.0
    heat_action:
      - switch.turn_on: relay
    idle_action:
      - switch.turn_off: relay
    on_state:
      then:
        - binary_sensor.template.publish:
            id: konvector_state
            state: !lambda 'return x.mode == climate::CLIMATE_MODE_HEAT;'

# Глобальные переменные для пикового времени
globals:
  - id: thermostat_state_before_peak
    type: bool
    initial_value: 'false'
  - id: in_peak
    type: bool
    initial_value: 'false'

# Логика пикового времени
interval:
  - interval: 60s
    then:
      lambda: |-
        auto now = id(ntp_time).now();
        if (!now.is_valid()) return;
        
        int hour = now.hour;
        
        // Определяем пиковое время: утро 7:00-10:00, вечер 17:00-21:00
        bool is_peak = (hour >= 7 && hour < 10) || (hour >= 17 && hour < 21);
        bool was_in_peak = id(in_peak);
        
        if (is_peak && !was_in_peak && id(switch_peack_off).state) {
          {
          // Вход в пиковое время - сохраняем состояние
          id(thermostat_state_before_peak) = (id(thermostat_garage_konvector).mode == climate::CLIMATE_MODE_HEAT);
          id(in_peak) = true;
          // Выключаем термостат
          auto call = id(thermostat_garage_konvector).make_call();
          call.set_mode(climate::CLIMATE_MODE_OFF);
          call.perform();
          }
        } else if (!is_peak && was_in_peak) {
          {
          // Выход из пикового времени - восстанавливаем состояние
          id(in_peak) = false;
          if (id(thermostat_state_before_peak)) {
            auto call = id(thermostat_garage_konvector).make_call();
            call.set_mode(climate::CLIMATE_MODE_HEAT);
            call.perform();
          }
          }
        }
