
esphome:
  name: garage-konvector
  friendly_name: garage_konvector

esp8266:
  board: sonoff_th

logger:

api:
  encryption:
    key: "Ldm49FmXtWzGqzHLQaf91mkPmK/Ajq1lrKILY05+NgE="

ota:
  - platform: esphome
    password: "0cf2d59e134cf13be87b10fd500c2e19"

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    - ssid: OpenWrt_Garage
      password: "9514210798"

  ap:
    ssid: "Garage-Thermostat-Konvector"
    password: "XN2wmpQxIxit"

captive_portal:
    