esphome:
  name: light-spalnya
  friendly_name: Light-spalnya
  on_boot:
    then: 
      - light.turn_off:
          id: spalnya_lamp

bk72xx:
  board: generic-bk7231t-qfn32-tuya

# Enable logging
# logger:

# Enable Home Assistant API
api:
  encryption:
    key: "qCjpTNX9sXnnVBRc3fIUNk6eZbFFdlajRnAq944XSPk="
  reboot_timeout: 1800s
  
ota:
  platform: esphome
  password: "1ed8692bea4dd2b457b73501f671d338"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
# Отправляем в сеть свой бинарный сенсор (binary_switch)
udp:
  binary_sensors:
    - binary_switch

text_sensor:
  - platform: libretiny
    version:
      name: LibreTiny Version
      
  - platform: wifi_info
    ip_address:
      name: IP Address ${device_name}
    ssid:
      name: SSID

binary_sensor:
  # Принимаем из сети бинаный сенсор (binary_switch_1 из выключателей бра) и управляем им основным светом
  - platform: udp
    provider: brah-spalnya
    id: binary_switch_bra_1
    remote_id: binary_switch_1
    internal: true
    on_click:
      - min_length: 510ms
        max_length: 5000ms
        then:
          light.toggle: spalnya_lamp

  - platform: udp
    provider: brah-spalnya
    id: binary_switch_bra_2
    remote_id: binary_switch_2
    internal: true
    on_click:
      - min_length: 510ms
        max_length: 5000ms
        then:
          light.toggle: spalnya_lamp

  - platform: gpio
    id: binary_switch
    pin:
      number: P6
      inverted: true
      mode: INPUT_PULLUP
    on_click:
      - min_length: 10ms
        max_length: 500ms
        then:
          - light.toggle: spalnya_lamp
          - if:
              condition:
                light.is_off: spalnya_lamp
              then:
                light.turn_on:
                  id: status_led_1
                  effect: "strobe"
              else:
                - light.turn_off: status_led_1
                
# ================== Счетик времени включенного света =======================
sensor:
  - platform: duty_time
    id: lightspalnya_work_time
    name: Light Spalnya Время работы
    icon: mdi:alarm-plus
    update_interval: 10s
    accuracy_decimals: 0
    device_class: duration
    lambda: "return id(spalnya_lamp).current_values.is_on() == true;"
    restore: true
    last_time:
      name: Light Spalnya посл. время работы
# ===================================================================================
  - platform: wifi_signal
    name: WiFi Strength ${device_name}
    update_interval: 60s
    id: wifi_signal_db
  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent ${device_name}"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
    device_class: ""

# == Пин реле света ==        
output:
  - id: light_output
    platform: gpio
    pin: P24
# ====================
light:
  - platform: binary
    name: "Light Spalnya"
    id: spalnya_lamp
    output: light_output
    icon: mdi:ceiling-light-outline
    restore_mode: RESTORE_DEFAULT_OFF
# ============================================================================

  - platform: status_led
    name: "status_led"
    id: status_led_1
    pin:
      number: P7
      inverted: true
    effects:
      - strobe:
          name: "strobe"
          colors:
            - state: true
              brightness: 100%
              duration: 500ms
            - state: false
              duration: 250ms