esphome:
  name: "light-kichen-stol"

bk72xx:
  board: generic-bk7231t-qfn32-tuya

api:
  encryption:
    key: "5t8f5uBHvcrDHBooumDy3auqKcceRsymI+323/oadDU="

ota:
  platform: esphome
  
wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    - ssid: Keenetic-Home
      password: "9994554500"
  ap:
    ssid: "Garage Dangeres Hotspot"
    password: "00000000"

binary_sensor:
  - platform: gpio
    id: binary_switch_1
    pin:
      number: P6
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      then:
        - light.toggle: kitchen_stol_lamp
        
output:
  - id: light_output
    platform: gpio
    pin: P24

light:
  - platform: binary
    name: "Light Kihen Stol"
    id: kitchen_stol_lamp
    output: light_output
    icon: mdi:light-flood-down
    restore_mode: RESTORE_DEFAULT_OFF

status_led:
  pin:
    number: P7
    inverted: true

    