esphome:
  name: test
  on_boot:
    - delay: 7s
    - lvgl.widget.hide: boot_screen

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:

<<: !include lvgl\lvgl.yaml
<<: !include display\display.yaml
<<: !include sensors\sensors.yaml

climate: !include climate\climate.yaml
font: !include font\font.yaml

api:
  encryption:
    key: "qsQmKLMvLh9REAS68i5MFrn5GKYXswAaDVRsCVhWNfw="

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: Keenetic-Home
  password: "9994554500"
  on_connect:
    then:
      - lvgl.widget.show: lbl_wifitatus

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"
    password: "2BgdJnlx1D7T"

udp:
captive_portal:

switch:
  - platform: gpio
    id: relay
    name: Relay 2
    pin: GPIO15

output:
  - platform: ledc
    pin: GPIO2
    id: backlight_pwm

light:
  - platform: monochromatic
    output: backlight_pwm
    name: "Display Backlight"
    id: back_light
    restore_mode: RESTORE_DEFAULT_ON

text:
  - platform: lvgl
    id: state_text
    widget: lbl_state
    name: "Thermostat state text"
    mode: text 
    internal: true


# interval:
#   - interval: 10s
#     then:
image:
  - file: https://esphome.io/_static/favicon-512x512.png
    id: boot_logo
    resize: 80x80
    type: RGB565
    use_transparency: true

